[package]
name = "indexset"
version = "0.3.2"
edition = "2021"
documentation = "https://docs.rs/indexset/"
repository = "https://github.com/brurucy/indexset"
license = "Apache-2.0 OR MIT"
description = "A two-level BTree with fast iteration and indexing operations"
keywords = ["btreemap", "btreeset", "set", "map"]
categories = ["data-structures"]
readme = "README.md"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
rand = "0.8.5"

[dependencies]
serde = { version = "1.0.151", optional = true, features = ["derive"] }
ftree = { version = "0.1.0", features = ["serde"] }

[features]
serde = ["dep:serde"]

[[bench]]
name = "stdlib"
harness = false